using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace PcapReplayer.Tests
{
    [TestClass]
    public class TrcConverterTests
    {
        // ── Shared Test Data & Helpers ────────────────────────────────────────

        private static string BuildMinimalTrc(IEnumerable<string> rxLines)
        {
            var sb = new StringBuilder();
            sb.AppendLine(";$FILEVERSION=1.1");
            sb.AppendLine(";$STARTTIME=46140.6177158796");
            sb.AppendLine(";");
            sb.AppendLine(";   Start time: 4/28/2026 14:49:30.652.0");
            sb.AppendLine(";   Generated by PCAN-View v6.0.0.1040");
            sb.AppendLine(";");
            sb.AppendLine(";   Message Number");
            sb.AppendLine(";   |         Time Offset (ms)");
            sb.AppendLine(";   |         |        Type");
            sb.AppendLine(";   |         |        |        ID (hex)");
            sb.AppendLine(";   |         |        |        |     Data Length");
            sb.AppendLine(";   |         |        |        |     |   Data Bytes (hex) ...");
            sb.AppendLine(";   |         |        |        |     |   |");
            sb.AppendLine(";---+--   ----+----  --+--  ----+---  +  -+ -- -- -- -- -- -- --");
            int lineNum = 1;
            foreach (var line in rxLines)
            {
                sb.AppendLine($" {lineNum,4}) {line}");
                lineNum++;
            }
            return sb.ToString();
        }

        private static string GetTempFile(string ext)
            => Path.Combine(Path.GetTempPath(), $"trc_test_{Guid.NewGuid():N}{ext}");

        private static List<byte[]> ParsePcapUdpPayloads(string pcapPath)
        {
            var payloads = new List<byte[]>();
            using var fs = File.OpenRead(pcapPath);
            using var br = new BinaryReader(fs);

            // Skip 24-byte global header
            br.ReadBytes(24);

            while (fs.Position < fs.Length)
            {
                // packet header
                br.ReadUInt32(); // ts_sec
                br.ReadUInt32(); // ts_usec
                uint incl_len = br.ReadUInt32();
                br.ReadUInt32(); // orig_len
                byte[] pkt = br.ReadBytes((int)incl_len);

                // Ethernet(14) + IP(20) + UDP(8) = 42 bytes header
                if (pkt.Length > 42)
                {
                    byte[] payload = new byte[pkt.Length - 42];
                    Array.Copy(pkt, 42, payload, 0, payload.Length);
                    payloads.Add(payload);
                }
            }
            return payloads;
        }

        // ══════════════════════════════════════════════════════════════════════
        //  Parsing Tests
        // ══════════════════════════════════════════════════════════════════════

        [TestMethod]
        public void Convert_EmptyFile_ThrowsInvalidOperation()
        {
            string trcPath = GetTempFile(".trc");
            string outPath = GetTempFile(".pcap");
            try
            {
                File.WriteAllText(trcPath, "");
                var opts = new TrcConversionOptions { TrcFile = trcPath, OutputPcap = outPath };
                
                Assert.ThrowsException<InvalidOperationException>(() => TrcConverter.Convert(opts));
            }
            finally
            {
                File.Delete(trcPath);
                if (File.Exists(outPath)) File.Delete(outPath);
            }
        }

        [TestMethod]
        public void Convert_HeaderOnly_ThrowsInvalidOperation()
        {
            string trcPath = GetTempFile(".trc");
            string outPath = GetTempFile(".pcap");
            try
            {
                File.WriteAllText(trcPath, BuildMinimalTrc(Array.Empty<string>()));
                var opts = new TrcConversionOptions { TrcFile = trcPath, OutputPcap = outPath };

                Assert.ThrowsException<InvalidOperationException>(() => TrcConverter.Convert(opts));
            }
            finally
            {
                File.Delete(trcPath);
                if (File.Exists(outPath)) File.Delete(outPath);
            }
        }

        [TestMethod]
        public void Convert_ValidRxLines_ParsesCorrectly()
        {
            string trcPath = GetTempFile(".trc");
            string outPath = GetTempFile(".pcap");
            try
            {
                string trcData = BuildMinimalTrc(new[]
                {
                    "       23.6  Rx     18F140CA  8  01 1E 00 28 00 00 00 00",
                    "       24.7  Rx     18F141CA  8  01 14 00 00 00 FF FF FF"
                });
                File.WriteAllText(trcPath, trcData);

                var opts = new TrcConversionOptions
                {
                    TrcFile = trcPath,
                    OutputPcap = outPath,
                    MetadataHeader = "TEST|1",
                    FramesPerPacket = 10
                };

                var res = TrcConverter.Convert(opts);

                Assert.AreEqual(2, res.FramesParsed);
                Assert.AreEqual(1, res.PacketsWritten);
                Assert.AreEqual(0, res.Warnings.Count);

                var payloads = ParsePcapUdpPayloads(outPath);
                Assert.AreEqual(1, payloads.Count);
                
                // Payload length = "TEST|1".Length (6) + (2 * 13) = 32
                Assert.AreEqual(32, payloads[0].Length);
            }
            finally
            {
                File.Delete(trcPath);
                if (File.Exists(outPath)) File.Delete(outPath);
            }
        }

        [TestMethod]
        public void Convert_InvalidLines_AddsWarningsAndContinues()
        {
            string trcPath = GetTempFile(".trc");
            string outPath = GetTempFile(".pcap");
            try
            {
                string trcData = BuildMinimalTrc(new[]
                {
                    "       23.6  Rx     18F140CA  8  01 1E 00 28 00 00 00 00", // valid
                    "       XX.X  Rx     18F141CA  8  00",                      // invalid time
                    "       25.0  Rx     NOTHEX    8  00",                      // invalid ID
                    "       26.0  Rx     100       9  00",                      // DLC > 8
                    "       27.0  Rx     18F141CA  8  01 14 00 00 00 FF FF FF"  // valid
                });
                File.WriteAllText(trcPath, trcData);

                var opts = new TrcConversionOptions { TrcFile = trcPath, OutputPcap = outPath };
                var res = TrcConverter.Convert(opts);

                Assert.AreEqual(2, res.FramesParsed);
                Assert.AreEqual(1, res.Warnings.Count); // Only the DLC > 8 line hits the warning. The rest fail the regex!
            }
            finally
            {
                File.Delete(trcPath);
                if (File.Exists(outPath)) File.Delete(outPath);
            }
        }

        // ══════════════════════════════════════════════════════════════════════
        //  Batching Tests
        // ══════════════════════════════════════════════════════════════════════

        [TestMethod]
        public void Convert_ExceedsBatchThresholdMs_SplitsPackets()
        {
            string trcPath = GetTempFile(".trc");
            string outPath = GetTempFile(".pcap");
            try
            {
                string trcData = BuildMinimalTrc(new[]
                {
                    "        1.0  Rx     100  8  00",
                    "        2.0  Rx     101  8  00", // delta 1.0 (batch 1)
                    "       10.0  Rx     102  8  00", // delta 9.0 > 5.0 (batch 2 starts)
                    "       12.0  Rx     103  8  00", // delta 2.0 (batch 2)
                    "       20.0  Rx     104  8  00"  // delta 10.0 > 5.0 (batch 3 starts)
                });
                File.WriteAllText(trcPath, trcData);

                var opts = new TrcConversionOptions
                {
                    TrcFile = trcPath,
                    OutputPcap = outPath,
                    BatchThresholdMs = 5.0,
                    FramesPerPacket = 100,
                    MetadataHeader = "META"
                };

                var res = TrcConverter.Convert(opts);

                Assert.AreEqual(5, res.FramesParsed);
                Assert.AreEqual(3, res.PacketsWritten);

                var payloads = ParsePcapUdpPayloads(outPath);
                Assert.AreEqual(3, payloads.Count);

                // Batch 1: "META" + 2 frames
                Assert.AreEqual(4 + 26, payloads[0].Length);
                // Batch 2: 2 frames (no meta)
                Assert.AreEqual(26, payloads[1].Length);
                // Batch 3: 1 frame (no meta)
                Assert.AreEqual(13, payloads[2].Length);
            }
            finally
            {
                File.Delete(trcPath);
                if (File.Exists(outPath)) File.Delete(outPath);
            }
        }

        [TestMethod]
        public void Convert_ExceedsFramesPerPacket_SplitsPackets()
        {
            string trcPath = GetTempFile(".trc");
            string outPath = GetTempFile(".pcap");
            try
            {
                // 5 frames all close together in time
                string trcData = BuildMinimalTrc(new[]
                {
                    "        1.0  Rx     100  8  00",
                    "        1.1  Rx     101  8  00",
                    "        1.2  Rx     102  8  00",
                    "        1.3  Rx     103  8  00",
                    "        1.4  Rx     104  8  00"
                });
                File.WriteAllText(trcPath, trcData);

                var opts = new TrcConversionOptions
                {
                    TrcFile = trcPath,
                    OutputPcap = outPath,
                    BatchThresholdMs = 100.0,
                    FramesPerPacket = 2, // limit 2 per packet
                    MetadataHeader = "META"
                };

                var res = TrcConverter.Convert(opts);

                Assert.AreEqual(5, res.FramesParsed);
                // 5 frames / 2 per packet = 3 packets (2, 2, 1)
                Assert.AreEqual(3, res.PacketsWritten);

                var payloads = ParsePcapUdpPayloads(outPath);
                Assert.AreEqual(3, payloads.Count);

                // Batch 1: "META" + 2 frames
                Assert.AreEqual(4 + 26, payloads[0].Length);
                // Batch 2: 2 frames (no meta)
                Assert.AreEqual(26, payloads[1].Length);
                // Batch 3: 1 frame (no meta)
                Assert.AreEqual(13, payloads[2].Length);
            }
            finally
            {
                File.Delete(trcPath);
                if (File.Exists(outPath)) File.Delete(outPath);
            }
        }

        // ══════════════════════════════════════════════════════════════════════
        //  USR Frame Layout Tests (Directly testing the helper method)
        // ══════════════════════════════════════════════════════════════════════

        [TestMethod]
        public void BuildUsrFrame_ExtendedId_SetsBit7()
        {
            var f = new TrcCanFrame(1.0, 0x18F140CA, true, 8, new byte[] { 1, 2, 3, 4, 5, 6, 7, 8 });
            byte[] usr = TrcConverter.BuildUsrFrame(f);

            Assert.AreEqual(13, usr.Length);
            
            // Info byte: bit7(EXT)=1, DLC=8 => 0x88
            Assert.AreEqual(0x88, usr[0]);
            
            // ID big-endian (29-bit)
            Assert.AreEqual(0x18, usr[1]);
            Assert.AreEqual(0xF1, usr[2]);
            Assert.AreEqual(0x40, usr[3]);
            Assert.AreEqual(0xCA, usr[4]);

            // Data
            Assert.AreEqual(1, usr[5]);
            Assert.AreEqual(8, usr[12]);
        }

        [TestMethod]
        public void BuildUsrFrame_StandardId_ClearsBit7()
        {
            var f = new TrcCanFrame(1.0, 0x1A4, false, 4, new byte[] { 0xAA, 0xBB, 0xCC, 0xDD });
            byte[] usr = TrcConverter.BuildUsrFrame(f);

            Assert.AreEqual(13, usr.Length);
            
            // Info byte: bit7(EXT)=0, DLC=4 => 0x04
            Assert.AreEqual(0x04, usr[0]);
            
            // ID big-endian (29-bit zero padded)
            Assert.AreEqual(0x00, usr[1]);
            Assert.AreEqual(0x00, usr[2]);
            Assert.AreEqual(0x01, usr[3]);
            Assert.AreEqual(0xA4, usr[4]);

            // Data (zero padded to 8 bytes)
            Assert.AreEqual(0xAA, usr[5]);
            Assert.AreEqual(0xDD, usr[8]);
            Assert.AreEqual(0x00, usr[9]);
            Assert.AreEqual(0x00, usr[12]);
        }
        
        // ══════════════════════════════════════════════════════════════════════
        //  UDP Packet Builder Tests
        // ══════════════════════════════════════════════════════════════════════

        [TestMethod]
        public void BuildUdpPacket_PopulatesHeadersCorrectly()
        {
            byte[] payload = new byte[] { 0x11, 0x22, 0x33, 0x44 };
            byte[] pkt = TrcConverter.BuildUdpPacket("10.0.0.1", "10.0.0.2", 1234, 5678, payload);
            
            Assert.AreEqual(14 + 20 + 8 + 4, pkt.Length); // 46 bytes

            // Check IP Source (offset 14 + 12 = 26)
            Assert.AreEqual(10, pkt[26]);
            Assert.AreEqual(0, pkt[27]);
            Assert.AreEqual(0, pkt[28]);
            Assert.AreEqual(1, pkt[29]);

            // Check IP Dest (offset 14 + 16 = 30)
            Assert.AreEqual(10, pkt[30]);
            Assert.AreEqual(0, pkt[31]);
            Assert.AreEqual(0, pkt[32]);
            Assert.AreEqual(2, pkt[33]);

            // Check UDP Source Port (offset 34) - 1234 = 0x04D2
            Assert.AreEqual(0x04, pkt[34]);
            Assert.AreEqual(0xD2, pkt[35]);

            // Check UDP Dest Port (offset 36) - 5678 = 0x162E
            Assert.AreEqual(0x16, pkt[36]);
            Assert.AreEqual(0x2E, pkt[37]);
            
            // Check Payload (offset 42)
            Assert.AreEqual(0x11, pkt[42]);
            Assert.AreEqual(0x44, pkt[45]);
        }
    }
}
